# Generated by Django 3.0.6 on 2020-05-16 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='bug_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='bug',
            name='open_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date opened'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date started'),
        ),
        migrations.CreateModel(
            name='Worknote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Bug')),
            ],
        ),
    ]
