# Generated by Django 3.0.6 on 2020-05-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200516_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
